name: dl
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.1.0
  - absl-py=0.9.0
  - astor=0.7.1
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - blosc=1.19.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.6.20
  - certifi=2020.6.20
  - charls=2.1.0
  - cloudpickle=1.4.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cytoolz=0.10.1
  - dask-core=2.19.0
  - decorator=4.4.2
  - freetype=2.10.2
  - gast=0.3.3
  - gcc_impl_linux-64=7.5.0
  - gcc_linux-64=7.5.0
  - giflib=5.2.1
  - google-pasta=0.2.0
  - grpcio=1.27.2
  - gxx_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - h5py=2.10.0
  - hdf5=1.10.5
  - icu=64.2
  - imagecodecs=2020.5.30
  - imageio=2.8.0
  - importlib-metadata=1.6.1
  - jpeg=9d
  - jxrlib=1.1
  - keras=2.2.4
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.2.0
  - lcms2=2.11
  - ld_impl_linux-64=2.34
  - libaec=1.0.4
  - libblas=3.8.0
  - libcblas=3.8.0
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.5.0
  - libgomp=9.2.0
  - libgpuarray=0.7.6
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.12.3
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libwebp-base=1.1.0
  - libzopfli=1.0.3
  - lz4-c=1.9.2
  - mako=1.1.0
  - markdown=3.2.2
  - markupsafe=1.1.1
  - matplotlib-base=3.2.2
  - ncurses=6.1
  - networkx=2.4
  - numpy=1.18.5
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1g
  - pandas=1.0.5
  - pillow=7.1.2
  - pip=20.1.1
  - protobuf=3.12.3
  - pygpu=0.7.6
  - pyparsing=2.4.7
  - python=3.6.10
  - python-dateutil=2.8.1
  - python_abi=3.6
  - pytz=2020.1
  - pywavelets=1.1.1
  - pyyaml=5.3.1
  - readline=8.0
  - scikit-image=0.17.2
  - scipy=1.4.1
  - setuptools=47.3.1
  - six=1.15.0
  - snappy=1.1.8
  - sqlite=3.30.1
  - tensorboard=1.14.0
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - theano=1.0.4
  - tifffile=2020.6.3
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - werkzeug=1.0.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xz=5.2.5
  - yaml=0.2.5
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - attrs==19.3.0
    - backcall==0.2.0
    - bleach==3.1.5
    - csbdeep==0.6.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - ipykernel==5.3.0
    - ipython==7.15.0
    - jedi==0.17.1
    - joblib==0.15.1
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.3
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - memory-profiler==0.57.0
    - mistune==0.8.4
    - n2v==0.1.11
    - nbconvert==5.6.1
    - nbformat==5.0.7
    - notebook==6.0.3
    - packaging==20.4
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.5
    - psutil==5.7.0
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyrsistent==0.16.0
    - pyzmq==19.0.1
    - qtconsole==4.7.5
    - qtpy==1.9.0
    - scikit-learn==0.23.1
    - send2trash==1.5.0
    - sklearn==0.0
    - terminado==0.8.3
    - testpath==0.4.4
    - threadpoolctl==2.1.0
    - tqdm==4.46.1
    - wcwidth==0.2.4
    - webencodings==0.5.1
    - stardist==0.7.1
